name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *" # 00:00 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4

      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          COMMITTER_NAME: "github-actions[bot]"
          COMMITTER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit & Push
        run: |
          git config user.name "fr297"
          git config user.email "fr297@users.noreply.github.com"
          git add -A .
          git commit -m "generated" || echo "No changes"
          git push
